/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author jpoou
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLImage = new javax.swing.JLabel();
        jBCreated = new javax.swing.JButton();
        jTName = new javax.swing.JTextField();
        jBCancel = new javax.swing.JButton();
        jTSurname = new javax.swing.JTextField();
        jTaddress = new javax.swing.JTextField();
        jTPhone = new javax.swing.JTextField();
        jTDate = new javax.swing.JTextField();
        jTNationality = new javax.swing.JTextField();
        jLTitle = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLName = new javax.swing.JLabel();
        jBFile = new javax.swing.JButton();
        jLSurname = new javax.swing.JLabel();
        JRmale = new javax.swing.JRadioButton();
        jLSex = new javax.swing.JLabel();
        jRFemale = new javax.swing.JRadioButton();
        jLAddress = new javax.swing.JLabel();
        jLPhote = new javax.swing.JLabel();
        jLDate = new javax.swing.JLabel();
        jLNationality = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda - Editar");

        jLImage.setText("Fotografía");

        jBCreated.setText("Crear");
        jBCreated.setToolTipText("Crear contacto");

        jBCancel.setText("Cancelar");

        jTPhone.setToolTipText("");
        jTPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPhoneKeyTyped(evt);
            }
        });

        jLTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLTitle.setText("Editar contacto");

        jLName.setText("Nombre");

        jBFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_ic_attach_file_48px_352032.png"))); // NOI18N
        jBFile.setBorder(null);

        jLSurname.setText("Apellido");

        JRmale.setText("Masculino");

        jLSex.setText("Sexo");

        jRFemale.setText("Femenino");

        jLAddress.setText("Direccion");

        jLPhote.setText("Telefono");

        jLDate.setText("Fecha de nacimiento");

        jLNationality.setText("Nacionalidad");

        jLEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLName)
                                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDate)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addComponent(jLSurname)
                                        .addComponent(jLPhote)
                                        .addComponent(jTPhone))
                                    .addComponent(jTDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLAddress)
                            .addComponent(jLSex)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JRmale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRFemale))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLNationality, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLEmail)
                                    .addComponent(jTEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLImage)
                                .addGap(18, 18, 18)
                                .addComponent(jBFile))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLTitle)))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCancel)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLTitle)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLSurname)
                                    .addComponent(jLName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLSex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JRmale)
                                            .addComponent(jRFemale)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLPhote)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDate)
                                .addGap(7, 7, 7)
                                .addComponent(jTDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEmail)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLNationality)
                                .addGap(3, 3, 3)
                                .addComponent(jTNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLImage)
                    .addComponent(jBFile))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCreated)
                    .addComponent(jBCancel))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPhoneKeyTyped
        char c = evt.getKeyChar() ;
                
            if (!   ((c==KeyEvent.VK_DELETE) 
                ||  (c== KeyEvent.VK_ENTER)      || (c == KeyEvent.VK_TAB) 
                ||  (Character.isDigit(c)))) 
            {
               evt.consume() ;
           } 
    }//GEN-LAST:event_jTPhoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton JRmale;
    public javax.swing.JButton jBCancel;
    public javax.swing.JButton jBCreated;
    public javax.swing.JButton jBFile;
    private javax.swing.JLabel jLAddress;
    private javax.swing.JLabel jLDate;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLImage;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLNationality;
    private javax.swing.JLabel jLPhote;
    private javax.swing.JLabel jLSex;
    private javax.swing.JLabel jLSurname;
    private javax.swing.JLabel jLTitle;
    public javax.swing.JRadioButton jRFemale;
    public javax.swing.JTextField jTDate;
    public javax.swing.JTextField jTEmail;
    public javax.swing.JTextField jTName;
    public javax.swing.JTextField jTNationality;
    public javax.swing.JTextField jTPhone;
    public javax.swing.JTextField jTSurname;
    public javax.swing.JTextField jTaddress;
    // End of variables declaration//GEN-END:variables
}
